/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formpendaftaran;

import java.awt.*;
import java.awt.print.*;
import java.sql.*;
import java.text.NumberFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class EditCetak extends javax.swing.JFrame {

    /**
     * Creates new form EditCetak
     */
    public EditCetak() {
        initComponents();
    }
    
    public void print() {
        try {
            PrinterJob pjob = PrinterJob.getPrinterJob();
            pjob.setJobName("Formulir Pendaftaran");
            pjob.setCopies(1);
            pjob.setPrintable(new Printable() {
                public int print(Graphics g1, PageFormat pf, int pageNum) {
                    if (pageNum > 0) {
                        return Printable.NO_SUCH_PAGE; // end of job
                    }

                    Graphics2D g2 = (Graphics2D) g1;
                    g2.translate(pf.getImageableX(), pf.getImageableY());

                    g2.drawString("Pendaftaran Mahasiswa Baru 2024", 50, 50);
                    g2.drawString("Formulir Pendaftaran", 125, 70);

                    try {
                        konekDb rama = new konekDb();
                        Connection con = rama.Buka();
                        String userId = UserSession.getUserId();

                        String strsql = "SELECT f.nodaftar, f.full_name, f.tanggal, f.alamat, f.email, f.nohp, "
                                        + "p.jalur, p.prodi, p.biaya "
                                        + "FROM formdaftar f INNER JOIN prodi p ON f.nodaftar = p.nodaftar "
                                        + "WHERE f.id = ?";
                        PreparedStatement ps = con.prepareStatement(strsql);
                        ps.setString(1, userId);
                        ResultSet rs = ps.executeQuery();

                        int y = 100; // starting y position
                        float lineSpacing = 1.5f; // line spacing factor

                        while (rs.next()) {
                            drawLeftAlignedString(g2, "No. Pendaftaran", rs.getString("nodaftar"), 50, y);
                            y += 15 * lineSpacing;
                            drawLeftAlignedString(g2, "Nama Lengkap", rs.getString("full_name"), 50, y);
                            y += 15 * lineSpacing;
                            drawLeftAlignedString(g2, "Tanggal Lahir", rs.getString("tanggal"), 50, y);
                            y += 15 * lineSpacing;
                            drawLeftAlignedString(g2, "Alamat", rs.getString("alamat"), 50, y);
                            y += 15 * lineSpacing;
                            drawLeftAlignedString(g2, "Email", rs.getString("email"), 50, y);
                            y += 15 * lineSpacing;
                            drawLeftAlignedString(g2, "Nomor Telepon", rs.getString("nohp"), 50, y);
                            y += 15 * lineSpacing;
                            drawLeftAlignedString(g2, "Jalur Pendaftaran", rs.getString("jalur"), 50, y);
                            y += 15 * lineSpacing;
                            drawLeftAlignedString(g2, "Program Studi", rs.getString("prodi"), 50, y);
                            y += 15 * lineSpacing;
                            drawLeftAlignedString(g2, "Total Biaya", "Rp " + NumberFormat.getNumberInstance().format(rs.getInt("biaya")), 50, y);
                            y += 15 * lineSpacing;
                            y += 10; // space between data entries
                        }

                        rs.close();
                        ps.close();
                        con.close();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                    return Printable.PAGE_EXISTS;
                }
            });

            if (pjob.printDialog() == false) {
                return;
            }
            pjob.print();
        } catch (PrinterException pe) {
            pe.printStackTrace();
        }
    }

    private void drawLeftAlignedString(Graphics2D g2, String label, String value, int x, int y) {
        FontMetrics fm = g2.getFontMetrics();
        int labelWidth = fm.stringWidth(label + ": ");
        g2.drawString(label + ":", x, y); // label
        g2.drawString(value, x + labelWidth + 10, y); // value, dengan penyesuaian posisi
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edit = new javax.swing.JButton();
        cetak = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        edit.setBackground(new java.awt.Color(0, 255, 51));
        edit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Edit Data");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        cetak.setBackground(new java.awt.Color(51, 51, 255));
        cetak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cetak.setForeground(new java.awt.Color(255, 255, 255));
        cetak.setText("Cetak Formulir");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("PENDAFTARAN TELAH SELESAI");

        jLabel2.setText("Silahkan pilih menu dibawah ini");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cetak)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        print();
    }//GEN-LAST:event_cetakActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        String userId = UserSession.getUserId();
        try {
            konekDb rama = new konekDb();
            Connection con = rama.Buka();

            // Query untuk memeriksa apakah sudah ada data di tabel formdaftar untuk userId tertentu
            String checkFormDaftarQuery = "SELECT COUNT(*) AS count FROM formdaftar WHERE id = ?";
            PreparedStatement checkFormDaftarStmt = con.prepareStatement(checkFormDaftarQuery);
            checkFormDaftarStmt.setString(1, userId);
            ResultSet formDaftarRs = checkFormDaftarStmt.executeQuery();

            if (formDaftarRs.next() && formDaftarRs.getInt("count") > 0) {
                // Jika data formdaftar ada, lanjutkan memeriksa tabel prodi
                String checkProdiQuery = "SELECT COUNT(*) AS count FROM prodi WHERE nodaftar = (SELECT nodaftar FROM formdaftar WHERE id = ?)";
                PreparedStatement checkProdiStmt = con.prepareStatement(checkProdiQuery);
                checkProdiStmt.setString(1, userId);
                ResultSet prodiRs = checkProdiStmt.executeQuery();

                if (prodiRs.next() && prodiRs.getInt("count") > 0) {
                    // Jika data prodi ada, buka halaman edit
                    this.dispose();
                    Fix editData = new Fix();
                    editData.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Anda belum mengisi form prodi.");
                }

                prodiRs.close();
                checkProdiStmt.close();
            } else {
                JOptionPane.showMessageDialog(this, "Anda belum mengisi form data diri.");
            }

            formDaftarRs.close();
            checkFormDaftarStmt.close();
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCetak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cetak;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
